### ISSUE TITLE
No module name import

### ISSUE THREAD

**Issue by trhubwork** [askedrelic/django-book#21]
Hello,
I started the Django Book and I continue to get:

 ' ~\Python35-32\python.exe: No module named import' 

errors.

I used an alias= in git bash to set 'python' to run python.exe.  I'm getting the 'No module named' error types when I run:

```
$django-admin.py startproject mysite'
'$ python -m manage.py runserver'

```

Here is an example of another error:

```
TR mysite$ python manage.py runserver
C:\Users\TR\AppData\Local\Programs\Python\Python35-32\python.exe: can't open file 'manage.py': [Errno 2] No such file or directory

```

Thanks for the help,

TR

**Comment by trhubwork** [comment]
I figured out the issue I was having in the above question.  I was not in the correct 'mysite' folder. . But I still have an issue with not getting the:

```
Validating models...
0 errors found.

Django version 1.0,.....
```

To appear in the Gitbash window.  I get the following message in my git bash with I type in the http://127.0.0.1:8000 into the browser:

```
[06/May/2016 13:00:51] "GET / HTTP/1.1" 200 1767
Not Found: /
```

Any idea why?

![firstdjangoserver](https://cloud.githubusercontent.com/assets/18382628/15083532/069600aa-138b-11e6-9d20-04f01863ea03.PNG)

**Comment by trhubwork** [comment]
I figured out my issues:

1.) needed to set up my path correctly 

2.) use './' 'python ./manage.py runserver' when starting the server.

3.) Finally remove '.defaults' from the top line of the url file when you edit it.

**Comment by askedrelic** [comment]
Great work! I know anecdotally that python on windows can be tricky. Also good to see you starting with Python 3.5...

Just an FYI, this repo and book are reasonably outdated. If you want fresher content, I would recommend 2 Scoops of Django https://www.twoscoopspress.com/products/two-scoops-of-django-1-8
